// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tts_backend.djinni

#pragma once

#include <functional>

namespace prism::java {

enum class BackendFeatures : int32_t {
    IS_SUPPORTED_AT_RUNTIME = 1 << 0,
    RESERVED = 1 << 1,
    SUPPORTS_SPEAK = 1 << 2,
    SUPPORTS_SPEAK_TO_MEMORY = 1 << 3,
    SUPPORTS_BRAILLE = 1 << 4,
    SUPPORTS_OUTPUT = 1 << 5,
    SUPPORTS_IS_SPEAKING = 1 << 6,
    SUPPORTS_STOP = 1 << 7,
    SUPPORTS_PAUSE = 1 << 8,
    SUPPORTS_RESUME = 1 << 9,
    SUPPORTS_SET_VOLUME = 1 << 10,
    SUPPORTS_GET_VOLUME = 1 << 11,
    SUPPORTS_SET_RATE = 1 << 12,
    SUPPORTS_GET_RATE = 1 << 13,
    SUPPORTS_SET_PITCH = 1 << 14,
    SUPPORTS_GET_PITCH = 1 << 15,
    SUPPORTS_REFRESH_VOICES = 1 << 16,
    SUPPORTS_COUNT_VOICES = 1 << 17,
    SUPPORTS_GET_VOICE_NAME = 1 << 18,
    SUPPORTS_GET_VOICE_LANGUAGE = 1 << 19,
    SUPPORTS_GET_VOICE = 1 << 20,
    SUPPORTS_SET_VOICE = 1 << 21,
    SUPPORTS_GET_CHANNELS = 1 << 22,
    SUPPORTS_GET_SAMPLE_RATE = 1 << 23,
    SUPPORTS_GET_BIT_DEPTH = 1 << 24,
    PERFORMS_SILENCE_TRIMMING_ON_SPEAK = 1 << 25,
    PERFORMS_SILENCE_TRIMMING_ON_SPEAK_TO_MEMORY = 1 << 26,
    SUPPORTS_SPEAK_SSML = 1 << 27,
    SUPPORTS_SPEAK_TO_MEMORY_SSML = 1 << 28,
};
constexpr BackendFeatures operator|(BackendFeatures lhs, BackendFeatures rhs) noexcept {
    return static_cast<BackendFeatures>(static_cast<int32_t>(lhs) | static_cast<int32_t>(rhs));
}
constexpr BackendFeatures& operator|=(BackendFeatures& lhs, BackendFeatures rhs) noexcept {
    return lhs = lhs | rhs;
}
constexpr BackendFeatures operator&(BackendFeatures lhs, BackendFeatures rhs) noexcept {
    return static_cast<BackendFeatures>(static_cast<int32_t>(lhs) & static_cast<int32_t>(rhs));
}
constexpr BackendFeatures& operator&=(BackendFeatures& lhs, BackendFeatures rhs) noexcept {
    return lhs = lhs & rhs;
}
constexpr BackendFeatures operator^(BackendFeatures lhs, BackendFeatures rhs) noexcept {
    return static_cast<BackendFeatures>(static_cast<int32_t>(lhs) ^ static_cast<int32_t>(rhs));
}
constexpr BackendFeatures& operator^=(BackendFeatures& lhs, BackendFeatures rhs) noexcept {
    return lhs = lhs ^ rhs;
}
constexpr BackendFeatures operator~(BackendFeatures x) noexcept {
    return static_cast<BackendFeatures>(~static_cast<int32_t>(x));
}

} // namespace prism::java

namespace std {

template <>
struct hash<::prism::java::BackendFeatures> {
    size_t operator()(::prism::java::BackendFeatures type) const {
        return std::hash<int32_t>()(static_cast<int32_t>(type));
    }
};

} // namespace std
