@ cdecl prism_speechd_abi_version()
@ cdecl prism_speechd_available()
@ cdecl prism_speechd_create(ptr)
@ cdecl prism_speechd_destroy(ptr)
@ cdecl prism_speechd_speak(ptr str long)
@ cdecl prism_speechd_stop(ptr)
@ cdecl prism_speechd_pause(ptr)
@ cdecl prism_speechd_resume(ptr)
@ cdecl prism_speechd_set_volume(ptr float)
@ cdecl prism_speechd_get_volume(ptr ptr)
@ cdecl prism_speechd_set_rate(ptr float)
@ cdecl prism_speechd_get_rate(ptr ptr)
@ cdecl prism_speechd_set_pitch(ptr float)
@ cdecl prism_speechd_get_pitch(ptr ptr)
@ cdecl prism_speechd_refresh_voices(ptr)
@ cdecl prism_speechd_count_voices(ptr ptr)
@ cdecl prism_speechd_get_voice_name(ptr long ptr long ptr)
@ cdecl prism_speechd_get_voice_language(ptr long ptr long ptr)
@ cdecl prism_speechd_set_voice(ptr long)
@ cdecl prism_speechd_get_voice(ptr ptr)
