// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tts_backend.djinni

#pragma once

#include "android/BackendFeatures.hpp"
#include "djinni/support/jni/djinni_support.hpp"

namespace prism::jni {

class BackendFeatures final : ::djinni::JniFlags {
public:
    using CppType = ::prism::java::BackendFeatures;
    using JniType = jobject;

    using Boxed = BackendFeatures;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<BackendFeatures>::get().flags(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<BackendFeatures>::get().create(jniEnv, static_cast<unsigned>(c), 29); }

private:
    BackendFeatures() : JniFlags("com/github/ethindp/prism/BackendFeatures") {}
    friend ::djinni::JniClass<BackendFeatures>;
};

} // namespace prism::jni
