# SPDX-License-Identifier: MPL-2.0

include_guard(GLOBAL)
include(PrismGuards)
include(CheckCXXSourceCompiles)
include(CheckIPOSupported)

if(MSVC_CXX_ARCHITECTURE_ID)
  set(_arch "${MSVC_CXX_ARCHITECTURE_ID}")
elseif(CMAKE_C_COMPILER_ARCHITECTURE_ID)
  set(_arch "${CMAKE_C_COMPILER_ARCHITECTURE_ID}")
else()
  set(_arch "${CMAKE_SYSTEM_PROCESSOR}")
endif()
string(TOLOWER "${_arch}" PRISM_ARCH)
if(PRISM_ARCH MATCHES "^(x64|amd64|x86_64)$")
  set(PRISM_ARCH_CLASS "x64")
elseif(PRISM_ARCH MATCHES "^(x86|i.86)$")
  set(PRISM_ARCH_CLASS "x86")
elseif(PRISM_ARCH MATCHES "^(arm64|aarch64)$")
  set(PRISM_ARCH_CLASS "arm64")
elseif(PRISM_ARCH STREQUAL "arm64ec")
  set(PRISM_ARCH_CLASS "arm64ec")
else()
  set(PRISM_ARCH_CLASS "unknown")
  message(WARNING "Prism: unrecognised target architecture '${PRISM_ARCH}'")
endif()
if(WIN32)
  set(PRISM_PLATFORM_MODULE "PlatformWindows")
elseif(ANDROID)
  set(PRISM_PLATFORM_MODULE "PlatformAndroid")
elseif(EMSCRIPTEN)
  set(PRISM_PLATFORM_MODULE "PlatformEmscripten")
elseif(APPLE)
  set(PRISM_PLATFORM_MODULE "PlatformApple")
elseif(UNIX)
  set(PRISM_PLATFORM_MODULE "PlatformUnix")
else()
  message(FATAL_ERROR "Prism: unsupported platform '${CMAKE_SYSTEM_NAME}'")
endif()
if(WIN32)
  string(TOLOWER "${CMAKE_HOST_SYSTEM_PROCESSOR}" _host)
  if(_host MATCHES "^(amd64|x86_64)$")
    set(PRISM_MIDL_HOST_DIR "x64")
  elseif(_host MATCHES "^(arm64|aarch64)$")
    set(PRISM_MIDL_HOST_DIR "arm64")
  elseif(_host MATCHES "^(x86|i.86)$")
    set(PRISM_MIDL_HOST_DIR "x86")
  else()
    set(PRISM_MIDL_HOST_DIR "x64")
  endif()
  if(PRISM_ARCH_CLASS STREQUAL "arm64")
    set(PRISM_MIDL_ENV "arm64")
  elseif(PRISM_ARCH_CLASS STREQUAL "x64" OR PRISM_ARCH_CLASS STREQUAL "arm64ec")
    set(PRISM_MIDL_ENV "x64")
  elseif(PRISM_ARCH_CLASS STREQUAL "x86")
    set(PRISM_MIDL_ENV "win32")
  else()
    message(
      FATAL_ERROR
        "Prism: cannot select a MIDL /env for architecture '${PRISM_ARCH}'.")
  endif()
endif()
if(NOT MSVC)
  set(_jthread_src
      "
#include <stop_token>
#include <thread>
int main() { std::jthread t([](std::stop_token st) {}); return 0; }
")
  check_cxx_source_compiles("${_jthread_src}" PRISM_HAS_JTHREAD_NATIVE)
  if(NOT PRISM_HAS_JTHREAD_NATIVE)
    set(CMAKE_REQUIRED_FLAGS "-fexperimental-library")
    set(CMAKE_REQUIRED_LINK_OPTIONS "-fexperimental-library")
    check_cxx_source_compiles("${_jthread_src}" PRISM_HAS_JTHREAD_EXPERIMENTAL)
    unset(CMAKE_REQUIRED_FLAGS)
    unset(CMAKE_REQUIRED_LINK_OPTIONS)
    if(NOT PRISM_HAS_JTHREAD_EXPERIMENTAL)
      message(
        FATAL_ERROR
          "Prism requires std::jthread. Your standard library provides it neither "
          "natively nor under -fexperimental-library.")
    endif()
  endif()
endif()
check_ipo_supported(RESULT PRISM_HAS_IPO OUTPUT _ipo_why)
if(ANDROID)
  set(PRISM_USE_IPO OFF)
elseif(PRISM_DIAGNOSE_VECTORIZATION)
  set(PRISM_USE_IPO OFF)
elseif(PRISM_HAS_IPO)
  set(PRISM_USE_IPO ON)
else()
  set(PRISM_USE_IPO OFF)
  message(STATUS "Prism: IPO unavailable (${_ipo_why})")
endif()
