@ cdecl prism_spiel_abi_version()
@ cdecl prism_spiel_available()
@ cdecl prism_spiel_create(ptr)
@ cdecl prism_spiel_destroy(ptr)
@ cdecl prism_spiel_speak(ptr str long)
@ cdecl prism_spiel_stop(ptr)
@ cdecl prism_spiel_pause(ptr)
@ cdecl prism_spiel_resume(ptr)
@ cdecl prism_spiel_is_speaking(ptr ptr)
@ cdecl prism_spiel_set_volume(ptr float)
@ cdecl prism_spiel_get_volume(ptr ptr)
@ cdecl prism_spiel_set_rate(ptr float)
@ cdecl prism_spiel_get_rate(ptr ptr)
@ cdecl prism_spiel_set_pitch(ptr float)
@ cdecl prism_spiel_get_pitch(ptr ptr)
@ cdecl prism_spiel_refresh_voices(ptr)
@ cdecl prism_spiel_count_voices(ptr ptr)
@ cdecl prism_spiel_get_voice_name(ptr long ptr long ptr)
@ cdecl prism_spiel_get_voice_language(ptr long ptr long ptr)
@ cdecl prism_spiel_set_voice(ptr long)
@ cdecl prism_spiel_get_voice(ptr ptr)
