/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Orca.Module */

#define TYPE_ORG_GNOME_ORCA_MODULE (org_gnome_orca_module_get_type ())
#define ORG_GNOME_ORCA_MODULE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_ORCA_MODULE, OrgGnomeOrcaModule))
#define IS_ORG_GNOME_ORCA_MODULE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_ORCA_MODULE))
#define ORG_GNOME_ORCA_MODULE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_GNOME_ORCA_MODULE, OrgGnomeOrcaModuleIface))

struct _OrgGnomeOrcaModule;
typedef struct _OrgGnomeOrcaModule OrgGnomeOrcaModule;
typedef struct _OrgGnomeOrcaModuleIface OrgGnomeOrcaModuleIface;

struct _OrgGnomeOrcaModuleIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_execute_command) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_command_name,
    gboolean arg_notify_user);

  gboolean (*handle_execute_parameterized_command) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_command_name,
    GVariant *arg_parameters,
    gboolean arg_notify_user);

  gboolean (*handle_execute_runtime_getter) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_getter_name);

  gboolean (*handle_execute_runtime_setter) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_setter_name,
    GVariant *arg_value);

  gboolean (*handle_list_commands) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_parameterized_commands) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_runtime_getters) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_runtime_setters) (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeOrcaModule, g_object_unref)
#endif

GType org_gnome_orca_module_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_gnome_orca_module_interface_info (void);
guint org_gnome_orca_module_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_gnome_orca_module_complete_execute_command (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    gboolean return);

void org_gnome_orca_module_complete_execute_parameterized_command (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);

void org_gnome_orca_module_complete_execute_runtime_getter (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);

void org_gnome_orca_module_complete_execute_runtime_setter (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    gboolean return);

void org_gnome_orca_module_complete_list_commands (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);

void org_gnome_orca_module_complete_list_parameterized_commands (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);

void org_gnome_orca_module_complete_list_runtime_getters (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);

void org_gnome_orca_module_complete_list_runtime_setters (
    OrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);



/* D-Bus method calls: */
void org_gnome_orca_module_call_execute_command (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    gboolean arg_notify_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_execute_command_finish (
    OrgGnomeOrcaModule *proxy,
    gboolean *out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_execute_command_sync (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    gboolean arg_notify_user,
    gboolean *out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_execute_parameterized_command (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    GVariant *arg_parameters,
    gboolean arg_notify_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_execute_parameterized_command_finish (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_execute_parameterized_command_sync (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    GVariant *arg_parameters,
    gboolean arg_notify_user,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_execute_runtime_getter (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_getter_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_execute_runtime_getter_finish (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_execute_runtime_getter_sync (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_getter_name,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_execute_runtime_setter (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_setter_name,
    GVariant *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_execute_runtime_setter_finish (
    OrgGnomeOrcaModule *proxy,
    gboolean *out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_execute_runtime_setter_sync (
    OrgGnomeOrcaModule *proxy,
    const gchar *arg_setter_name,
    GVariant *arg_value,
    gboolean *out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_list_commands (
    OrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_list_commands_finish (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_list_commands_sync (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_list_parameterized_commands (
    OrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_list_parameterized_commands_finish (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_list_parameterized_commands_sync (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_list_runtime_getters (
    OrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_list_runtime_getters_finish (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_list_runtime_getters_sync (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_module_call_list_runtime_setters (
    OrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_module_call_list_runtime_setters_finish (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_module_call_list_runtime_setters_sync (
    OrgGnomeOrcaModule *proxy,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_GNOME_ORCA_MODULE_PROXY (org_gnome_orca_module_proxy_get_type ())
#define ORG_GNOME_ORCA_MODULE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_ORCA_MODULE_PROXY, OrgGnomeOrcaModuleProxy))
#define ORG_GNOME_ORCA_MODULE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_ORCA_MODULE_PROXY, OrgGnomeOrcaModuleProxyClass))
#define ORG_GNOME_ORCA_MODULE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_ORCA_MODULE_PROXY, OrgGnomeOrcaModuleProxyClass))
#define IS_ORG_GNOME_ORCA_MODULE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_ORCA_MODULE_PROXY))
#define IS_ORG_GNOME_ORCA_MODULE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_ORCA_MODULE_PROXY))

typedef struct _OrgGnomeOrcaModuleProxy OrgGnomeOrcaModuleProxy;
typedef struct _OrgGnomeOrcaModuleProxyClass OrgGnomeOrcaModuleProxyClass;
typedef struct _OrgGnomeOrcaModuleProxyPrivate OrgGnomeOrcaModuleProxyPrivate;

struct _OrgGnomeOrcaModuleProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgGnomeOrcaModuleProxyPrivate *priv;
};

struct _OrgGnomeOrcaModuleProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_gnome_orca_module_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeOrcaModuleProxy, g_object_unref)
#endif

void org_gnome_orca_module_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeOrcaModule *org_gnome_orca_module_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeOrcaModule *org_gnome_orca_module_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_gnome_orca_module_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeOrcaModule *org_gnome_orca_module_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeOrcaModule *org_gnome_orca_module_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_GNOME_ORCA_MODULE_SKELETON (org_gnome_orca_module_skeleton_get_type ())
#define ORG_GNOME_ORCA_MODULE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_ORCA_MODULE_SKELETON, OrgGnomeOrcaModuleSkeleton))
#define ORG_GNOME_ORCA_MODULE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_ORCA_MODULE_SKELETON, OrgGnomeOrcaModuleSkeletonClass))
#define ORG_GNOME_ORCA_MODULE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_ORCA_MODULE_SKELETON, OrgGnomeOrcaModuleSkeletonClass))
#define IS_ORG_GNOME_ORCA_MODULE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_ORCA_MODULE_SKELETON))
#define IS_ORG_GNOME_ORCA_MODULE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_ORCA_MODULE_SKELETON))

typedef struct _OrgGnomeOrcaModuleSkeleton OrgGnomeOrcaModuleSkeleton;
typedef struct _OrgGnomeOrcaModuleSkeletonClass OrgGnomeOrcaModuleSkeletonClass;
typedef struct _OrgGnomeOrcaModuleSkeletonPrivate OrgGnomeOrcaModuleSkeletonPrivate;

struct _OrgGnomeOrcaModuleSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgGnomeOrcaModuleSkeletonPrivate *priv;
};

struct _OrgGnomeOrcaModuleSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_gnome_orca_module_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeOrcaModuleSkeleton, g_object_unref)
#endif

OrgGnomeOrcaModule *org_gnome_orca_module_skeleton_new (void);


/* ---- */

#define TYPE_OBJECT (object_get_type ())
#define OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT, Object))
#define IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT))
#define OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_OBJECT, Object))

struct _Object;
typedef struct _Object Object;
typedef struct _ObjectIface ObjectIface;

struct _ObjectIface
{
  GTypeInterface parent_iface;
};

GType object_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Object, g_object_unref)
#endif

OrgGnomeOrcaModule *object_get_org_gnome_orca_module (Object *object);
OrgGnomeOrcaModule *object_peek_org_gnome_orca_module (Object *object);

#define TYPE_OBJECT_PROXY (object_proxy_get_type ())
#define OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_PROXY, ObjectProxy))
#define OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_PROXY))
#define IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_PROXY))

typedef struct _ObjectProxy ObjectProxy;
typedef struct _ObjectProxyClass ObjectProxyClass;
typedef struct _ObjectProxyPrivate ObjectProxyPrivate;

struct _ObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  ObjectProxyPrivate *priv;
};

struct _ObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectProxy, g_object_unref)
#endif

ObjectProxy *object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define TYPE_OBJECT_SKELETON (object_skeleton_get_type ())
#define OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_SKELETON, ObjectSkeleton))
#define OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_SKELETON))
#define IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_SKELETON))

typedef struct _ObjectSkeleton ObjectSkeleton;
typedef struct _ObjectSkeletonClass ObjectSkeletonClass;
typedef struct _ObjectSkeletonPrivate ObjectSkeletonPrivate;

struct _ObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  ObjectSkeletonPrivate *priv;
};

struct _ObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectSkeleton, g_object_unref)
#endif

ObjectSkeleton *object_skeleton_new (const gchar *object_path);
void object_skeleton_set_org_gnome_orca_module (ObjectSkeleton *object, OrgGnomeOrcaModule *interface_);

/* ---- */

#define TYPE_OBJECT_MANAGER_CLIENT (object_manager_client_get_type ())
#define OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClient))
#define OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_MANAGER_CLIENT))
#define IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _ObjectManagerClient ObjectManagerClient;
typedef struct _ObjectManagerClientClass ObjectManagerClientClass;
typedef struct _ObjectManagerClientPrivate ObjectManagerClientPrivate;

struct _ObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  ObjectManagerClientPrivate *priv;
};

struct _ObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectManagerClient, g_object_unref)
#endif

GType object_manager_client_get_type (void) G_GNUC_CONST;

GType object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS
