/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Orca.Service */

#define TYPE_ORG_GNOME_ORCA_SERVICE (org_gnome_orca_service_get_type ())
#define ORG_GNOME_ORCA_SERVICE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_ORCA_SERVICE, OrgGnomeOrcaService))
#define IS_ORG_GNOME_ORCA_SERVICE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_ORCA_SERVICE))
#define ORG_GNOME_ORCA_SERVICE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_ORG_GNOME_ORCA_SERVICE, OrgGnomeOrcaServiceIface))

struct _OrgGnomeOrcaService;
typedef struct _OrgGnomeOrcaService OrgGnomeOrcaService;
typedef struct _OrgGnomeOrcaServiceIface OrgGnomeOrcaServiceIface;

struct _OrgGnomeOrcaServiceIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_get_version) (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_commands) (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_modules) (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_present_message) (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_message);

  gboolean (*handle_quit) (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_show_preferences) (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeOrcaService, g_object_unref)
#endif

GType org_gnome_orca_service_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *org_gnome_orca_service_interface_info (void);
guint org_gnome_orca_service_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void org_gnome_orca_service_complete_get_version (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    const gchar *return);

void org_gnome_orca_service_complete_list_commands (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    GVariant *return);

void org_gnome_orca_service_complete_list_modules (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *return);

void org_gnome_orca_service_complete_present_message (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    gboolean return);

void org_gnome_orca_service_complete_quit (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    gboolean return);

void org_gnome_orca_service_complete_show_preferences (
    OrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    gboolean return);



/* D-Bus method calls: */
void org_gnome_orca_service_call_get_version (
    OrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_service_call_get_version_finish (
    OrgGnomeOrcaService *proxy,
    gchar **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_service_call_get_version_sync (
    OrgGnomeOrcaService *proxy,
    gchar **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_service_call_list_commands (
    OrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_service_call_list_commands_finish (
    OrgGnomeOrcaService *proxy,
    GVariant **out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_service_call_list_commands_sync (
    OrgGnomeOrcaService *proxy,
    GVariant **out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_service_call_list_modules (
    OrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_service_call_list_modules_finish (
    OrgGnomeOrcaService *proxy,
    gchar ***out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_service_call_list_modules_sync (
    OrgGnomeOrcaService *proxy,
    gchar ***out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_service_call_present_message (
    OrgGnomeOrcaService *proxy,
    const gchar *arg_message,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_service_call_present_message_finish (
    OrgGnomeOrcaService *proxy,
    gboolean *out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_service_call_present_message_sync (
    OrgGnomeOrcaService *proxy,
    const gchar *arg_message,
    gboolean *out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_service_call_quit (
    OrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_service_call_quit_finish (
    OrgGnomeOrcaService *proxy,
    gboolean *out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_service_call_quit_sync (
    OrgGnomeOrcaService *proxy,
    gboolean *out_return,
    GCancellable *cancellable,
    GError **error);

void org_gnome_orca_service_call_show_preferences (
    OrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean org_gnome_orca_service_call_show_preferences_finish (
    OrgGnomeOrcaService *proxy,
    gboolean *out_return,
    GAsyncResult *res,
    GError **error);

gboolean org_gnome_orca_service_call_show_preferences_sync (
    OrgGnomeOrcaService *proxy,
    gboolean *out_return,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define TYPE_ORG_GNOME_ORCA_SERVICE_PROXY (org_gnome_orca_service_proxy_get_type ())
#define ORG_GNOME_ORCA_SERVICE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_ORCA_SERVICE_PROXY, OrgGnomeOrcaServiceProxy))
#define ORG_GNOME_ORCA_SERVICE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_ORCA_SERVICE_PROXY, OrgGnomeOrcaServiceProxyClass))
#define ORG_GNOME_ORCA_SERVICE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_ORCA_SERVICE_PROXY, OrgGnomeOrcaServiceProxyClass))
#define IS_ORG_GNOME_ORCA_SERVICE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_ORCA_SERVICE_PROXY))
#define IS_ORG_GNOME_ORCA_SERVICE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_ORCA_SERVICE_PROXY))

typedef struct _OrgGnomeOrcaServiceProxy OrgGnomeOrcaServiceProxy;
typedef struct _OrgGnomeOrcaServiceProxyClass OrgGnomeOrcaServiceProxyClass;
typedef struct _OrgGnomeOrcaServiceProxyPrivate OrgGnomeOrcaServiceProxyPrivate;

struct _OrgGnomeOrcaServiceProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrgGnomeOrcaServiceProxyPrivate *priv;
};

struct _OrgGnomeOrcaServiceProxyClass
{
  GDBusProxyClass parent_class;
};

GType org_gnome_orca_service_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeOrcaServiceProxy, g_object_unref)
#endif

void org_gnome_orca_service_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeOrcaService *org_gnome_orca_service_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeOrcaService *org_gnome_orca_service_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void org_gnome_orca_service_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrgGnomeOrcaService *org_gnome_orca_service_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrgGnomeOrcaService *org_gnome_orca_service_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON (org_gnome_orca_service_skeleton_get_type ())
#define ORG_GNOME_ORCA_SERVICE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON, OrgGnomeOrcaServiceSkeleton))
#define ORG_GNOME_ORCA_SERVICE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON, OrgGnomeOrcaServiceSkeletonClass))
#define ORG_GNOME_ORCA_SERVICE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON, OrgGnomeOrcaServiceSkeletonClass))
#define IS_ORG_GNOME_ORCA_SERVICE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON))
#define IS_ORG_GNOME_ORCA_SERVICE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON))

typedef struct _OrgGnomeOrcaServiceSkeleton OrgGnomeOrcaServiceSkeleton;
typedef struct _OrgGnomeOrcaServiceSkeletonClass OrgGnomeOrcaServiceSkeletonClass;
typedef struct _OrgGnomeOrcaServiceSkeletonPrivate OrgGnomeOrcaServiceSkeletonPrivate;

struct _OrgGnomeOrcaServiceSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrgGnomeOrcaServiceSkeletonPrivate *priv;
};

struct _OrgGnomeOrcaServiceSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType org_gnome_orca_service_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrgGnomeOrcaServiceSkeleton, g_object_unref)
#endif

OrgGnomeOrcaService *org_gnome_orca_service_skeleton_new (void);


/* ---- */

#define TYPE_OBJECT (object_get_type ())
#define OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT, Object))
#define IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT))
#define OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), TYPE_OBJECT, Object))

struct _Object;
typedef struct _Object Object;
typedef struct _ObjectIface ObjectIface;

struct _ObjectIface
{
  GTypeInterface parent_iface;
};

GType object_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (Object, g_object_unref)
#endif

OrgGnomeOrcaService *object_get_org_gnome_orca_service (Object *object);
OrgGnomeOrcaService *object_peek_org_gnome_orca_service (Object *object);

#define TYPE_OBJECT_PROXY (object_proxy_get_type ())
#define OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_PROXY, ObjectProxy))
#define OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_PROXY, ObjectProxyClass))
#define IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_PROXY))
#define IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_PROXY))

typedef struct _ObjectProxy ObjectProxy;
typedef struct _ObjectProxyClass ObjectProxyClass;
typedef struct _ObjectProxyPrivate ObjectProxyPrivate;

struct _ObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  ObjectProxyPrivate *priv;
};

struct _ObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectProxy, g_object_unref)
#endif

ObjectProxy *object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define TYPE_OBJECT_SKELETON (object_skeleton_get_type ())
#define OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_SKELETON, ObjectSkeleton))
#define OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_SKELETON, ObjectSkeletonClass))
#define IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_SKELETON))
#define IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_SKELETON))

typedef struct _ObjectSkeleton ObjectSkeleton;
typedef struct _ObjectSkeletonClass ObjectSkeletonClass;
typedef struct _ObjectSkeletonPrivate ObjectSkeletonPrivate;

struct _ObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  ObjectSkeletonPrivate *priv;
};

struct _ObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectSkeleton, g_object_unref)
#endif

ObjectSkeleton *object_skeleton_new (const gchar *object_path);
void object_skeleton_set_org_gnome_orca_service (ObjectSkeleton *object, OrgGnomeOrcaService *interface_);

/* ---- */

#define TYPE_OBJECT_MANAGER_CLIENT (object_manager_client_get_type ())
#define OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClient))
#define OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), TYPE_OBJECT_MANAGER_CLIENT, ObjectManagerClientClass))
#define IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), TYPE_OBJECT_MANAGER_CLIENT))
#define IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _ObjectManagerClient ObjectManagerClient;
typedef struct _ObjectManagerClientClass ObjectManagerClientClass;
typedef struct _ObjectManagerClientPrivate ObjectManagerClientPrivate;

struct _ObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  ObjectManagerClientPrivate *priv;
};

struct _ObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (ObjectManagerClient, g_object_unref)
#endif

GType object_manager_client_get_type (void) G_GNUC_CONST;

GType object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS
