/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Orca.Module */

#define ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE (orca_module_org_gnome_orca_module_get_type ())
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE, OrcaModuleOrgGnomeOrcaModule))
#define ORCA_MODULE_IS_ORG_GNOME_ORCA_MODULE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE))
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE, OrcaModuleOrgGnomeOrcaModuleIface))

struct _OrcaModuleOrgGnomeOrcaModule;
typedef struct _OrcaModuleOrgGnomeOrcaModule OrcaModuleOrgGnomeOrcaModule;
typedef struct _OrcaModuleOrgGnomeOrcaModuleIface OrcaModuleOrgGnomeOrcaModuleIface;

struct _OrcaModuleOrgGnomeOrcaModuleIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_execute_command) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_command_name,
    gboolean arg_notify_user);

  gboolean (*handle_execute_parameterized_command) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_command_name,
    GVariant *arg_parameters,
    gboolean arg_notify_user);

  gboolean (*handle_execute_runtime_getter) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_getter_name);

  gboolean (*handle_execute_runtime_setter) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_setter_name,
    GVariant *arg_value);

  gboolean (*handle_list_commands) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_parameterized_commands) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_runtime_getters) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_runtime_setters) (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleOrgGnomeOrcaModule, g_object_unref)
#endif

GType orca_module_org_gnome_orca_module_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *orca_module_org_gnome_orca_module_interface_info (void);
guint orca_module_org_gnome_orca_module_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void orca_module_org_gnome_orca_module_complete_execute_command (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    gboolean result);

void orca_module_org_gnome_orca_module_complete_execute_parameterized_command (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);

void orca_module_org_gnome_orca_module_complete_execute_runtime_getter (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);

void orca_module_org_gnome_orca_module_complete_execute_runtime_setter (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    gboolean result);

void orca_module_org_gnome_orca_module_complete_list_commands (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);

void orca_module_org_gnome_orca_module_complete_list_parameterized_commands (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);

void orca_module_org_gnome_orca_module_complete_list_runtime_getters (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);

void orca_module_org_gnome_orca_module_complete_list_runtime_setters (
    OrcaModuleOrgGnomeOrcaModule *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);



/* D-Bus method calls: */
void orca_module_org_gnome_orca_module_call_execute_command (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    gboolean arg_notify_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_execute_command_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    gboolean *out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_execute_command_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    gboolean arg_notify_user,
    gboolean *out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_execute_parameterized_command (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    GVariant *arg_parameters,
    gboolean arg_notify_user,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_execute_parameterized_command_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_execute_parameterized_command_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_command_name,
    GVariant *arg_parameters,
    gboolean arg_notify_user,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_execute_runtime_getter (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_getter_name,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_execute_runtime_getter_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_execute_runtime_getter_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_getter_name,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_execute_runtime_setter (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_setter_name,
    GVariant *arg_value,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_execute_runtime_setter_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    gboolean *out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_execute_runtime_setter_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    const gchar *arg_setter_name,
    GVariant *arg_value,
    gboolean *out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_list_commands (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_list_commands_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_list_commands_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_list_parameterized_commands (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_list_parameterized_commands_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_list_parameterized_commands_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_list_runtime_getters (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_list_runtime_getters_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_list_runtime_getters_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_module_org_gnome_orca_module_call_list_runtime_setters (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_module_org_gnome_orca_module_call_list_runtime_setters_finish (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_module_org_gnome_orca_module_call_list_runtime_setters_sync (
    OrcaModuleOrgGnomeOrcaModule *proxy,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_PROXY (orca_module_org_gnome_orca_module_proxy_get_type ())
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_PROXY, OrcaModuleOrgGnomeOrcaModuleProxy))
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_PROXY, OrcaModuleOrgGnomeOrcaModuleProxyClass))
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_PROXY, OrcaModuleOrgGnomeOrcaModuleProxyClass))
#define ORCA_MODULE_IS_ORG_GNOME_ORCA_MODULE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_PROXY))
#define ORCA_MODULE_IS_ORG_GNOME_ORCA_MODULE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_PROXY))

typedef struct _OrcaModuleOrgGnomeOrcaModuleProxy OrcaModuleOrgGnomeOrcaModuleProxy;
typedef struct _OrcaModuleOrgGnomeOrcaModuleProxyClass OrcaModuleOrgGnomeOrcaModuleProxyClass;
typedef struct _OrcaModuleOrgGnomeOrcaModuleProxyPrivate OrcaModuleOrgGnomeOrcaModuleProxyPrivate;

struct _OrcaModuleOrgGnomeOrcaModuleProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrcaModuleOrgGnomeOrcaModuleProxyPrivate *priv;
};

struct _OrcaModuleOrgGnomeOrcaModuleProxyClass
{
  GDBusProxyClass parent_class;
};

GType orca_module_org_gnome_orca_module_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleOrgGnomeOrcaModuleProxy, g_object_unref)
#endif

void orca_module_org_gnome_orca_module_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrcaModuleOrgGnomeOrcaModule *orca_module_org_gnome_orca_module_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrcaModuleOrgGnomeOrcaModule *orca_module_org_gnome_orca_module_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void orca_module_org_gnome_orca_module_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrcaModuleOrgGnomeOrcaModule *orca_module_org_gnome_orca_module_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrcaModuleOrgGnomeOrcaModule *orca_module_org_gnome_orca_module_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_SKELETON (orca_module_org_gnome_orca_module_skeleton_get_type ())
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_SKELETON, OrcaModuleOrgGnomeOrcaModuleSkeleton))
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_SKELETON, OrcaModuleOrgGnomeOrcaModuleSkeletonClass))
#define ORCA_MODULE_ORG_GNOME_ORCA_MODULE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_SKELETON, OrcaModuleOrgGnomeOrcaModuleSkeletonClass))
#define ORCA_MODULE_IS_ORG_GNOME_ORCA_MODULE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_SKELETON))
#define ORCA_MODULE_IS_ORG_GNOME_ORCA_MODULE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_MODULE_TYPE_ORG_GNOME_ORCA_MODULE_SKELETON))

typedef struct _OrcaModuleOrgGnomeOrcaModuleSkeleton OrcaModuleOrgGnomeOrcaModuleSkeleton;
typedef struct _OrcaModuleOrgGnomeOrcaModuleSkeletonClass OrcaModuleOrgGnomeOrcaModuleSkeletonClass;
typedef struct _OrcaModuleOrgGnomeOrcaModuleSkeletonPrivate OrcaModuleOrgGnomeOrcaModuleSkeletonPrivate;

struct _OrcaModuleOrgGnomeOrcaModuleSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrcaModuleOrgGnomeOrcaModuleSkeletonPrivate *priv;
};

struct _OrcaModuleOrgGnomeOrcaModuleSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType orca_module_org_gnome_orca_module_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleOrgGnomeOrcaModuleSkeleton, g_object_unref)
#endif

OrcaModuleOrgGnomeOrcaModule *orca_module_org_gnome_orca_module_skeleton_new (void);


/* ---- */

#define ORCA_MODULE_TYPE_OBJECT (orca_module_object_get_type ())
#define ORCA_MODULE_OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_OBJECT, OrcaModuleObject))
#define ORCA_MODULE_IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_OBJECT))
#define ORCA_MODULE_OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ORCA_MODULE_TYPE_OBJECT, OrcaModuleObject))

struct _OrcaModuleObject;
typedef struct _OrcaModuleObject OrcaModuleObject;
typedef struct _OrcaModuleObjectIface OrcaModuleObjectIface;

struct _OrcaModuleObjectIface
{
  GTypeInterface parent_iface;
};

GType orca_module_object_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleObject, g_object_unref)
#endif

OrcaModuleOrgGnomeOrcaModule *orca_module_object_get_org_gnome_orca_module (OrcaModuleObject *object);
OrcaModuleOrgGnomeOrcaModule *orca_module_object_peek_org_gnome_orca_module (OrcaModuleObject *object);

#define ORCA_MODULE_TYPE_OBJECT_PROXY (orca_module_object_proxy_get_type ())
#define ORCA_MODULE_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_OBJECT_PROXY, OrcaModuleObjectProxy))
#define ORCA_MODULE_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_MODULE_TYPE_OBJECT_PROXY, OrcaModuleObjectProxyClass))
#define ORCA_MODULE_OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_MODULE_TYPE_OBJECT_PROXY, OrcaModuleObjectProxyClass))
#define ORCA_MODULE_IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_OBJECT_PROXY))
#define ORCA_MODULE_IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_MODULE_TYPE_OBJECT_PROXY))

typedef struct _OrcaModuleObjectProxy OrcaModuleObjectProxy;
typedef struct _OrcaModuleObjectProxyClass OrcaModuleObjectProxyClass;
typedef struct _OrcaModuleObjectProxyPrivate OrcaModuleObjectProxyPrivate;

struct _OrcaModuleObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  OrcaModuleObjectProxyPrivate *priv;
};

struct _OrcaModuleObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType orca_module_object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleObjectProxy, g_object_unref)
#endif

OrcaModuleObjectProxy *orca_module_object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define ORCA_MODULE_TYPE_OBJECT_SKELETON (orca_module_object_skeleton_get_type ())
#define ORCA_MODULE_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_OBJECT_SKELETON, OrcaModuleObjectSkeleton))
#define ORCA_MODULE_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_MODULE_TYPE_OBJECT_SKELETON, OrcaModuleObjectSkeletonClass))
#define ORCA_MODULE_OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_MODULE_TYPE_OBJECT_SKELETON, OrcaModuleObjectSkeletonClass))
#define ORCA_MODULE_IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_OBJECT_SKELETON))
#define ORCA_MODULE_IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_MODULE_TYPE_OBJECT_SKELETON))

typedef struct _OrcaModuleObjectSkeleton OrcaModuleObjectSkeleton;
typedef struct _OrcaModuleObjectSkeletonClass OrcaModuleObjectSkeletonClass;
typedef struct _OrcaModuleObjectSkeletonPrivate OrcaModuleObjectSkeletonPrivate;

struct _OrcaModuleObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  OrcaModuleObjectSkeletonPrivate *priv;
};

struct _OrcaModuleObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType orca_module_object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleObjectSkeleton, g_object_unref)
#endif

OrcaModuleObjectSkeleton *orca_module_object_skeleton_new (const gchar *object_path);
void orca_module_object_skeleton_set_org_gnome_orca_module (OrcaModuleObjectSkeleton *object, OrcaModuleOrgGnomeOrcaModule *interface_);

/* ---- */

#define ORCA_MODULE_TYPE_OBJECT_MANAGER_CLIENT (orca_module_object_manager_client_get_type ())
#define ORCA_MODULE_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_MODULE_TYPE_OBJECT_MANAGER_CLIENT, OrcaModuleObjectManagerClient))
#define ORCA_MODULE_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_MODULE_TYPE_OBJECT_MANAGER_CLIENT, OrcaModuleObjectManagerClientClass))
#define ORCA_MODULE_OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_MODULE_TYPE_OBJECT_MANAGER_CLIENT, OrcaModuleObjectManagerClientClass))
#define ORCA_MODULE_IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_MODULE_TYPE_OBJECT_MANAGER_CLIENT))
#define ORCA_MODULE_IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_MODULE_TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _OrcaModuleObjectManagerClient OrcaModuleObjectManagerClient;
typedef struct _OrcaModuleObjectManagerClientClass OrcaModuleObjectManagerClientClass;
typedef struct _OrcaModuleObjectManagerClientPrivate OrcaModuleObjectManagerClientPrivate;

struct _OrcaModuleObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  OrcaModuleObjectManagerClientPrivate *priv;
};

struct _OrcaModuleObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaModuleObjectManagerClient, g_object_unref)
#endif

GType orca_module_object_manager_client_get_type (void) G_GNUC_CONST;

GType orca_module_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void orca_module_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *orca_module_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *orca_module_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void orca_module_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *orca_module_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *orca_module_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS
