/*
 * This file is generated by gdbus-codegen, do not modify it.
 *
 * The license of this code is the same as for the D-Bus interface description
 * it was derived from. Note that it links to GLib, so must comply with the
 * LGPL linking clauses.
 */

#pragma once

#include <gio/gio.h>

G_BEGIN_DECLS


/* ------------------------------------------------------------------------ */
/* Declarations for org.gnome.Orca.Service */

#define ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE (orca_service_org_gnome_orca_service_get_type ())
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE, OrcaServiceOrgGnomeOrcaService))
#define ORCA_SERVICE_IS_ORG_GNOME_ORCA_SERVICE(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE))
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE, OrcaServiceOrgGnomeOrcaServiceIface))

struct _OrcaServiceOrgGnomeOrcaService;
typedef struct _OrcaServiceOrgGnomeOrcaService OrcaServiceOrgGnomeOrcaService;
typedef struct _OrcaServiceOrgGnomeOrcaServiceIface OrcaServiceOrgGnomeOrcaServiceIface;

struct _OrcaServiceOrgGnomeOrcaServiceIface
{
  GTypeInterface parent_iface;

  gboolean (*handle_get_version) (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_commands) (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_list_modules) (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_present_message) (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    const gchar *arg_message);

  gboolean (*handle_quit) (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

  gboolean (*handle_show_preferences) (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation);

};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceOrgGnomeOrcaService, g_object_unref)
#endif

GType orca_service_org_gnome_orca_service_get_type (void) G_GNUC_CONST;

GDBusInterfaceInfo *orca_service_org_gnome_orca_service_interface_info (void);
guint orca_service_org_gnome_orca_service_override_properties (GObjectClass *klass, guint property_id_begin);


/* D-Bus method call completion functions: */
void orca_service_org_gnome_orca_service_complete_get_version (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    const gchar *result);

void orca_service_org_gnome_orca_service_complete_list_commands (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    GVariant *result);

void orca_service_org_gnome_orca_service_complete_list_modules (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    const gchar *const *result);

void orca_service_org_gnome_orca_service_complete_present_message (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    gboolean result);

void orca_service_org_gnome_orca_service_complete_quit (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    gboolean result);

void orca_service_org_gnome_orca_service_complete_show_preferences (
    OrcaServiceOrgGnomeOrcaService *object,
    GDBusMethodInvocation *invocation,
    gboolean result);



/* D-Bus method calls: */
void orca_service_org_gnome_orca_service_call_get_version (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_service_org_gnome_orca_service_call_get_version_finish (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gchar **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_service_org_gnome_orca_service_call_get_version_sync (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gchar **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_service_org_gnome_orca_service_call_list_commands (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_service_org_gnome_orca_service_call_list_commands_finish (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GVariant **out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_service_org_gnome_orca_service_call_list_commands_sync (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GVariant **out_result,
    GCancellable *cancellable,
    GError **error);

void orca_service_org_gnome_orca_service_call_list_modules (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_service_org_gnome_orca_service_call_list_modules_finish (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gchar ***out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_service_org_gnome_orca_service_call_list_modules_sync (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gchar ***out_result,
    GCancellable *cancellable,
    GError **error);

void orca_service_org_gnome_orca_service_call_present_message (
    OrcaServiceOrgGnomeOrcaService *proxy,
    const gchar *arg_message,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_service_org_gnome_orca_service_call_present_message_finish (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gboolean *out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_service_org_gnome_orca_service_call_present_message_sync (
    OrcaServiceOrgGnomeOrcaService *proxy,
    const gchar *arg_message,
    gboolean *out_result,
    GCancellable *cancellable,
    GError **error);

void orca_service_org_gnome_orca_service_call_quit (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_service_org_gnome_orca_service_call_quit_finish (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gboolean *out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_service_org_gnome_orca_service_call_quit_sync (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gboolean *out_result,
    GCancellable *cancellable,
    GError **error);

void orca_service_org_gnome_orca_service_call_show_preferences (
    OrcaServiceOrgGnomeOrcaService *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data);

gboolean orca_service_org_gnome_orca_service_call_show_preferences_finish (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gboolean *out_result,
    GAsyncResult *res,
    GError **error);

gboolean orca_service_org_gnome_orca_service_call_show_preferences_sync (
    OrcaServiceOrgGnomeOrcaService *proxy,
    gboolean *out_result,
    GCancellable *cancellable,
    GError **error);



/* ---- */

#define ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_PROXY (orca_service_org_gnome_orca_service_proxy_get_type ())
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_PROXY, OrcaServiceOrgGnomeOrcaServiceProxy))
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_PROXY, OrcaServiceOrgGnomeOrcaServiceProxyClass))
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_PROXY, OrcaServiceOrgGnomeOrcaServiceProxyClass))
#define ORCA_SERVICE_IS_ORG_GNOME_ORCA_SERVICE_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_PROXY))
#define ORCA_SERVICE_IS_ORG_GNOME_ORCA_SERVICE_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_PROXY))

typedef struct _OrcaServiceOrgGnomeOrcaServiceProxy OrcaServiceOrgGnomeOrcaServiceProxy;
typedef struct _OrcaServiceOrgGnomeOrcaServiceProxyClass OrcaServiceOrgGnomeOrcaServiceProxyClass;
typedef struct _OrcaServiceOrgGnomeOrcaServiceProxyPrivate OrcaServiceOrgGnomeOrcaServiceProxyPrivate;

struct _OrcaServiceOrgGnomeOrcaServiceProxy
{
  /*< private >*/
  GDBusProxy parent_instance;
  OrcaServiceOrgGnomeOrcaServiceProxyPrivate *priv;
};

struct _OrcaServiceOrgGnomeOrcaServiceProxyClass
{
  GDBusProxyClass parent_class;
};

GType orca_service_org_gnome_orca_service_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceOrgGnomeOrcaServiceProxy, g_object_unref)
#endif

void orca_service_org_gnome_orca_service_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrcaServiceOrgGnomeOrcaService *orca_service_org_gnome_orca_service_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error);
OrcaServiceOrgGnomeOrcaService *orca_service_org_gnome_orca_service_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);

void orca_service_org_gnome_orca_service_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data);
OrcaServiceOrgGnomeOrcaService *orca_service_org_gnome_orca_service_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
OrcaServiceOrgGnomeOrcaService *orca_service_org_gnome_orca_service_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error);


/* ---- */

#define ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON (orca_service_org_gnome_orca_service_skeleton_get_type ())
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON, OrcaServiceOrgGnomeOrcaServiceSkeleton))
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON, OrcaServiceOrgGnomeOrcaServiceSkeletonClass))
#define ORCA_SERVICE_ORG_GNOME_ORCA_SERVICE_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON, OrcaServiceOrgGnomeOrcaServiceSkeletonClass))
#define ORCA_SERVICE_IS_ORG_GNOME_ORCA_SERVICE_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON))
#define ORCA_SERVICE_IS_ORG_GNOME_ORCA_SERVICE_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_SERVICE_TYPE_ORG_GNOME_ORCA_SERVICE_SKELETON))

typedef struct _OrcaServiceOrgGnomeOrcaServiceSkeleton OrcaServiceOrgGnomeOrcaServiceSkeleton;
typedef struct _OrcaServiceOrgGnomeOrcaServiceSkeletonClass OrcaServiceOrgGnomeOrcaServiceSkeletonClass;
typedef struct _OrcaServiceOrgGnomeOrcaServiceSkeletonPrivate OrcaServiceOrgGnomeOrcaServiceSkeletonPrivate;

struct _OrcaServiceOrgGnomeOrcaServiceSkeleton
{
  /*< private >*/
  GDBusInterfaceSkeleton parent_instance;
  OrcaServiceOrgGnomeOrcaServiceSkeletonPrivate *priv;
};

struct _OrcaServiceOrgGnomeOrcaServiceSkeletonClass
{
  GDBusInterfaceSkeletonClass parent_class;
};

GType orca_service_org_gnome_orca_service_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceOrgGnomeOrcaServiceSkeleton, g_object_unref)
#endif

OrcaServiceOrgGnomeOrcaService *orca_service_org_gnome_orca_service_skeleton_new (void);


/* ---- */

#define ORCA_SERVICE_TYPE_OBJECT (orca_service_object_get_type ())
#define ORCA_SERVICE_OBJECT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_OBJECT, OrcaServiceObject))
#define ORCA_SERVICE_IS_OBJECT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_OBJECT))
#define ORCA_SERVICE_OBJECT_GET_IFACE(o) (G_TYPE_INSTANCE_GET_INTERFACE ((o), ORCA_SERVICE_TYPE_OBJECT, OrcaServiceObject))

struct _OrcaServiceObject;
typedef struct _OrcaServiceObject OrcaServiceObject;
typedef struct _OrcaServiceObjectIface OrcaServiceObjectIface;

struct _OrcaServiceObjectIface
{
  GTypeInterface parent_iface;
};

GType orca_service_object_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceObject, g_object_unref)
#endif

OrcaServiceOrgGnomeOrcaService *orca_service_object_get_org_gnome_orca_service (OrcaServiceObject *object);
OrcaServiceOrgGnomeOrcaService *orca_service_object_peek_org_gnome_orca_service (OrcaServiceObject *object);

#define ORCA_SERVICE_TYPE_OBJECT_PROXY (orca_service_object_proxy_get_type ())
#define ORCA_SERVICE_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_OBJECT_PROXY, OrcaServiceObjectProxy))
#define ORCA_SERVICE_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_SERVICE_TYPE_OBJECT_PROXY, OrcaServiceObjectProxyClass))
#define ORCA_SERVICE_OBJECT_PROXY_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_SERVICE_TYPE_OBJECT_PROXY, OrcaServiceObjectProxyClass))
#define ORCA_SERVICE_IS_OBJECT_PROXY(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_OBJECT_PROXY))
#define ORCA_SERVICE_IS_OBJECT_PROXY_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_SERVICE_TYPE_OBJECT_PROXY))

typedef struct _OrcaServiceObjectProxy OrcaServiceObjectProxy;
typedef struct _OrcaServiceObjectProxyClass OrcaServiceObjectProxyClass;
typedef struct _OrcaServiceObjectProxyPrivate OrcaServiceObjectProxyPrivate;

struct _OrcaServiceObjectProxy
{
  /*< private >*/
  GDBusObjectProxy parent_instance;
  OrcaServiceObjectProxyPrivate *priv;
};

struct _OrcaServiceObjectProxyClass
{
  GDBusObjectProxyClass parent_class;
};

GType orca_service_object_proxy_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceObjectProxy, g_object_unref)
#endif

OrcaServiceObjectProxy *orca_service_object_proxy_new (GDBusConnection *connection, const gchar *object_path);

#define ORCA_SERVICE_TYPE_OBJECT_SKELETON (orca_service_object_skeleton_get_type ())
#define ORCA_SERVICE_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_OBJECT_SKELETON, OrcaServiceObjectSkeleton))
#define ORCA_SERVICE_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_SERVICE_TYPE_OBJECT_SKELETON, OrcaServiceObjectSkeletonClass))
#define ORCA_SERVICE_OBJECT_SKELETON_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_SERVICE_TYPE_OBJECT_SKELETON, OrcaServiceObjectSkeletonClass))
#define ORCA_SERVICE_IS_OBJECT_SKELETON(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_OBJECT_SKELETON))
#define ORCA_SERVICE_IS_OBJECT_SKELETON_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_SERVICE_TYPE_OBJECT_SKELETON))

typedef struct _OrcaServiceObjectSkeleton OrcaServiceObjectSkeleton;
typedef struct _OrcaServiceObjectSkeletonClass OrcaServiceObjectSkeletonClass;
typedef struct _OrcaServiceObjectSkeletonPrivate OrcaServiceObjectSkeletonPrivate;

struct _OrcaServiceObjectSkeleton
{
  /*< private >*/
  GDBusObjectSkeleton parent_instance;
  OrcaServiceObjectSkeletonPrivate *priv;
};

struct _OrcaServiceObjectSkeletonClass
{
  GDBusObjectSkeletonClass parent_class;
};

GType orca_service_object_skeleton_get_type (void) G_GNUC_CONST;

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceObjectSkeleton, g_object_unref)
#endif

OrcaServiceObjectSkeleton *orca_service_object_skeleton_new (const gchar *object_path);
void orca_service_object_skeleton_set_org_gnome_orca_service (OrcaServiceObjectSkeleton *object, OrcaServiceOrgGnomeOrcaService *interface_);

/* ---- */

#define ORCA_SERVICE_TYPE_OBJECT_MANAGER_CLIENT (orca_service_object_manager_client_get_type ())
#define ORCA_SERVICE_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_CAST ((o), ORCA_SERVICE_TYPE_OBJECT_MANAGER_CLIENT, OrcaServiceObjectManagerClient))
#define ORCA_SERVICE_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_CAST ((k), ORCA_SERVICE_TYPE_OBJECT_MANAGER_CLIENT, OrcaServiceObjectManagerClientClass))
#define ORCA_SERVICE_OBJECT_MANAGER_CLIENT_GET_CLASS(o) (G_TYPE_INSTANCE_GET_CLASS ((o), ORCA_SERVICE_TYPE_OBJECT_MANAGER_CLIENT, OrcaServiceObjectManagerClientClass))
#define ORCA_SERVICE_IS_OBJECT_MANAGER_CLIENT(o) (G_TYPE_CHECK_INSTANCE_TYPE ((o), ORCA_SERVICE_TYPE_OBJECT_MANAGER_CLIENT))
#define ORCA_SERVICE_IS_OBJECT_MANAGER_CLIENT_CLASS(k) (G_TYPE_CHECK_CLASS_TYPE ((k), ORCA_SERVICE_TYPE_OBJECT_MANAGER_CLIENT))

typedef struct _OrcaServiceObjectManagerClient OrcaServiceObjectManagerClient;
typedef struct _OrcaServiceObjectManagerClientClass OrcaServiceObjectManagerClientClass;
typedef struct _OrcaServiceObjectManagerClientPrivate OrcaServiceObjectManagerClientPrivate;

struct _OrcaServiceObjectManagerClient
{
  /*< private >*/
  GDBusObjectManagerClient parent_instance;
  OrcaServiceObjectManagerClientPrivate *priv;
};

struct _OrcaServiceObjectManagerClientClass
{
  GDBusObjectManagerClientClass parent_class;
};

#if GLIB_CHECK_VERSION(2, 44, 0)
G_DEFINE_AUTOPTR_CLEANUP_FUNC (OrcaServiceObjectManagerClient, g_object_unref)
#endif

GType orca_service_object_manager_client_get_type (void) G_GNUC_CONST;

GType orca_service_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data);

void orca_service_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *orca_service_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *orca_service_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);

void orca_service_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data);
GDBusObjectManager *orca_service_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error);
GDBusObjectManager *orca_service_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error);


G_END_DECLS
