// SPDX-License-Identifier: MPL-2.0

#ifndef PRISM_WINELIB_STATUS_H
#define PRISM_WINELIB_STATUS_H
#include <stdint.h>

#ifdef __cplusplus
#define PRISM_WINELIB_NOEXCEPT noexcept
#else
#define PRISM_WINELIB_NOEXCEPT
#endif

#define PRISM_SPEECHD_BRIDGE_ABI_VERSION 1U
#define PRISM_SPIEL_BRIDGE_ABI_VERSION 1U

typedef int32_t PrismWinelibStatus;

enum {
  PRISM_WINELIB_OK = 0,
  PRISM_WINELIB_INVALID_ARGUMENT = 1,
  PRISM_WINELIB_NOT_AVAILABLE = 2,
  PRISM_WINELIB_INTERNAL = 3,
  PRISM_WINELIB_SPEAK_FAILURE = 4,
  PRISM_WINELIB_RANGE = 5,
  PRISM_WINELIB_NO_VOICES = 6,
  PRISM_WINELIB_NOT_SPEAKING = 7,
  PRISM_WINELIB_NOT_PAUSED = 8,
  PRISM_WINELIB_ALREADY_PAUSED = 9,
  PRISM_WINELIB_UNDEFINED_STATE = 10,
  PRISM_WINELIB_BUFFER_TOO_SMALL = 11,
  PRISM_WINELIB_MEMORY = 12
};

#endif
