// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tts_backend Module

package com.github.ethindp.prism;

public final class TtsBackendModule {
  static {
    if (System.getProperty("java.vm.vendor").equals("The Android Project")) {
      Guard.initialize();
    }
  }

  private static final class Guard {
    private static native void initialize();
  }
}
