// AUTOGENERATED FILE - DO NOT MODIFY!
// This file was generated by Djinni from tts_backend.djinni

package com.github.ethindp.prism;

public final class Unit {

  public Unit() {}

  @Override
  public String toString() {
    return "Unit{" + "}";
  }
}
