# SPDX-License-Identifier: MPL-2.0
name: Build Windows
on:
  workflow_call:

jobs:
  windows:
    strategy:
      fail-fast: true
      matrix:
        include:
          - { name: x64,   msvc_arch: amd64,       extra_cmake: "" }
          - { name: arm64, msvc_arch: amd64_arm64,  extra_cmake: "-DCMAKE_SYSTEM_PROCESSOR=ARM64" }
    runs-on: windows-2025-vs2026
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: ${{ matrix.msvc_arch }}
      - name: Install current CMake
        uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
        with:
          cmakeVersion: latest
      - name: Build all configurations
        shell: pwsh
        run: |
          foreach ($shared in @("ON", "OFF")) {
            $linkage = if ($shared -eq "ON") { "dynamic" } else { "static" }
            foreach ($bt in @("Release", "Debug")) {
              $config = $bt.ToLower()
              cmake -B "build-${linkage}-${config}" `
                -G Ninja `
                -DPRISM_ENABLE_TESTS=OFF `
                -DPRISM_ENABLE_DEMOS=OFF `
                -DPRISM_ENABLE_SHIMS=ON `
                -DPRISM_ENABLE_LEGACY_BACKENDS=ON `
                "-DCMAKE_BUILD_TYPE=$bt" `
                "-DBUILD_SHARED_LIBS=$shared" `
                -DPRISM_ENABLE_GDEXTENSION=OFF ${{ matrix.extra_cmake }}
              cmake --build "build-${linkage}-${config}"
            }
          }
      - name: Package
        shell: pwsh
        run: |
          foreach ($shared in @("ON", "OFF")) {
            $linkage = if ($shared -eq "ON") { "dynamic" } else { "static" }
            foreach ($bt in @("Release", "Debug")) {
              $config = $bt.ToLower()
              if (Test-Path "dist/${linkage}/${config}") {
                Remove-Item "dist/${linkage}/${config}" -Recurse -Force
              }
              cmake --install "build-${linkage}-${config}" `
                    --prefix  "dist/${linkage}/${config}" `
                    --config  $bt
            }
          }
          Move-Item dist/dynamic/release/include dist/include
          Remove-Item dist/dynamic/debug/include,dist/static/release/include,dist/static/debug/include `
            -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item -Recurse LICENSES dist/
          Copy-Item NOTICE dist/
          Compress-Archive -Path dist/* -DestinationPath "prism-windows-${{ matrix.name }}.zip"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-${{ matrix.name }}
          path: prism-windows-${{ matrix.name }}.zip
