# SPDX-License-Identifier: MPL-2.0
name: Build Wheels
on:
  workflow_call:

jobs:
  wheels:
    name: Build wheels for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux-intel
            runs-on: ubuntu-latest
            archs: native
          - os: linux-arm
            runs-on: ubuntu-24.04-arm
            archs: native
          - os: windows-intel
            runs-on: windows-latest
            archs: native
          - os: windows-arm
            runs-on: windows-11-arm
            archs: native
          - os: macos-intel
            runs-on: macos-26-intel
            archs: native
          - os: macos-arm
            runs-on: macos-26
            archs: native
          - os: android-intel
            runs-on: ubuntu-latest
            platform: android
            archs: native
          - os: android-arm
            runs-on: ubuntu-latest
            platform: android
            archs: arm64_v8a
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install current CMake
        uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
        with:
          cmakeVersion: latest
      - name: Build wheels
        uses: pypa/cibuildwheel@1828c10ab37f080699c7b81cea34097c684a7074 # v4.2.0
        env:
          ANDROID_API_LEVEL: 26
          CIBW_PLATFORM: ${{ matrix.platform || 'auto' }}
          CIBW_ARCHS: ${{ matrix.archs || 'auto64' }}
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl
