# SPDX-License-Identifier: MPL-2.0
name: Build GDExtension
on:
  workflow_call:

jobs:
  linux-web:
    strategy:
      fail-fast: false
      matrix:
        target-type: [template_debug, template_release]
        target:
          - { platform: linux, arch: x86_64, os: ubuntu-latest,    system: x86_64-linux,  shell: default }
          - { platform: linux, arch: arm64,  os: ubuntu-24.04-arm, system: aarch64-linux, shell: default }
          - { platform: web,   arch: wasm32, os: ubuntu-latest,    system: x86_64-linux,  shell: emscripten }
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@33c9ab3ef95cd57c164d9d6eb1f9a46338538d41 # main
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://cache.nixos.org
            experimental-features = nix-command flakes
      - name: Configure and build
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.${{ matrix.target.system }}.${{ matrix.target.shell }}" -c ./tools/gdextension-nix.sh "${{ matrix.target.platform }}" "${{ matrix.target.arch }}" "${{ matrix.target-type }}"
      - name: Verify and fix binary name
        run: |
          ./tools/gdextension-fixname.sh "${{ matrix.target.platform }}" "${{ matrix.target.arch }}" "${{ matrix.target-type }}"
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gdextension-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.target-type }}
          path: gdextension/project/bin/**
  native:
    strategy:
      fail-fast: false
      matrix:
        target-type: [template_debug, template_release]
        target:
          - { platform: windows, arch: x86_64, os: windows-latest, msvc: amd64 }
          - { platform: windows, arch: arm64,  os: windows-latest, msvc: amd64_arm64 }
          - { platform: macos,   arch: arm64,  os: macos-26 }
          - { platform: macos,   arch: x86_64, os: macos-26 }
          - { platform: android, arch: x86_64, os: ubuntu-latest }
          - { platform: android, arch: arm64,  os: ubuntu-latest }
          - { platform: ios,     arch: arm64,  os: macos-26 }
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          persist-credentials: false
      - name: MSVC setup
        if: matrix.target.platform == 'windows'
        uses: ilammy/msvc-dev-cmd@0b201ec74fa43914dc39ae48a89fd1d8cb592756 # v1.13.0
        with:
          arch: ${{ matrix.target.msvc }}
      - name: Install current CMake
        uses: lukka/get-cmake@fffaaafeea488556c2c12dad60690008bc1caacb # v4.4.2
        with:
          cmakeVersion: latest
      - name: NDK setup
        if: matrix.target.platform == 'android'
        uses: nttld/setup-ndk@ed92fe6cadad69be94a966a7ee3271275e62f779 # v1.6.0
        id: setup-ndk
        with:
          ndk-version: r29
      - name: Configure and build
        shell: bash
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        run: |
          ./tools/gdextension-native.sh "${{ matrix.target.platform }}" "${{ matrix.target.arch }}" "${{ matrix.target-type }}"
      - name: Verify and fix binary name
        shell: bash
        run: |
          ./tools/gdextension-fixname.sh "${{ matrix.target.platform }}" "${{ matrix.target.arch }}" "${{ matrix.target-type }}"
      - name: Remove Windows ancillary files
        if: matrix.target.platform == 'windows'
        shell: pwsh
        run: |
          Remove-Item gdextension/project/bin/* -Include *.exp,*.lib,*.pdb -Recurse -Force -ErrorAction SilentlyContinue
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: gdextension-${{ matrix.target.platform }}-${{ matrix.target.arch }}-${{ matrix.target-type }}
          path: gdextension/project/bin/**
