# SPDX-License-Identifier: MPL-2.0
name: Build Linux
on:
  workflow_call:

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: x64,   os: ubuntu-latest,    system: x86_64-linux }
          - { name: arm64, os: ubuntu-24.04-arm, system: aarch64-linux }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://cache.nixos.org
            experimental-features = nix-command flakes
      - name: Build all configurations
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.${{ matrix.system }}.winelibs" -c ./tools/build-linux.sh
      - name: Package
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.${{ matrix.system }}.winelibs" -c ./tools/package-linux.sh "${{ matrix.name }}"
      - uses: actions/upload-artifact@v7
        with:
          name: linux-${{ matrix.name }}
          path: prism-linux-${{ matrix.name }}.zip
