# SPDX-License-Identifier: MPL-2.0
name: Build Emscripten
on:
  workflow_call:

jobs:
  emscripten:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://cache.nixos.org
            experimental-features = nix-command flakes
      - name: Build all configurations
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.x86_64-linux.emscripten" -c ./tools/build-emscripten.sh
      - name: Package
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.x86_64-linux.emscripten" -c ./tools/package-emscripten.sh
      - uses: actions/upload-artifact@v7
        with:
          name: wasm
          path: prism-wasm.zip
