# SPDX-License-Identifier: MPL-2.0
name: Build Docs
on:
  workflow_call:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build docs
        run: |
          cargo install --all-features mdbook
          mdbook build doc
      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: docs
          path: doc/book
