# SPDX-License-Identifier: MPL-2.0
name: Lint Linux
on:
  workflow_call:

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: x64,   os: ubuntu-latest,    system: x86_64-linux }
          - { name: arm64, os: ubuntu-24.04-arm, system: aarch64-linux }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://cache.nixos.org
            experimental-features = nix-command flakes
      - name: Lint all configurations
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.${{ matrix.system }}.lint" -c ./tools/lint-linux.sh
