# SPDX-License-Identifier: MPL-2.0
name: Lint Linux
on:
  workflow_call:

env:
  CMAKE_COMMON: >-
    -G Ninja
    -DPRISM_ENABLE_TESTS=OFF
    -DPRISM_ENABLE_DEMOS=OFF
    -DPRISM_ENABLE_LEGACY_BACKENDS=ON
    -DPRISM_ENABLE_SHIMS=ON
    -DPRISM_ENABLE_LINTING=ON

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: x64,   os: ubuntu-latest }
          - { name: arm64, os: ubuntu-24.04-arm }
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install deps
        run: |
          sudo apt-get install -y clang-18 clang-tidy-18 libc++-18-dev libc++abi-18-dev gcc-14 g++-14 libspeechd-dev libglib2.0-dev wine64-tools libdbus-1-dev build-essential meson ninja-build pkg-config git libglib2.0-bin libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgirepository1.0-dev gobject-introspection gi-docgen dbus-daemon python3 python3-tap python3-dbusmock
          sudo sed -i -E '/^Requires\.private:/ s/(, *libunwind\b)|(\blibunwind *, *)//' /usr/lib/*/pkgconfig/gstreamer-1.0.pc
          sudo update-alternatives --install /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-18 100
          git clone https://github.com/project-spiel/libspiel.git
          cd libspiel
          meson setup build --prefix=/usr/local -Dtests=false -Ddocs=false
          meson compile -C build
          sudo meson install -C build
          cd ..
          rm -rf libspiel
      - name: Lint all configurations
        run: |
          for shared in ON OFF; do
            linkage=$( [ "$shared" = "ON" ] && echo "dynamic" || echo "static" )
            for bt in Release Debug; do
              config=$(echo "$bt" | tr '[:upper:]' '[:lower:]')
              cmake -B "build-${linkage}-${config}" ${{ env.CMAKE_COMMON }} \
                -DCMAKE_BUILD_TYPE="$bt" \
                -DCMAKE_C_COMPILER=clang-18 \
                -DCMAKE_CXX_COMPILER=clang++-18 \
                -DCMAKE_CXX_FLAGS="-stdlib=libc++" \
                -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" \
                -DCMAKE_SHARED_LINKER_FLAGS="-stdlib=libc++" \
                -DCMAKE_C_CLANG_TIDY=/usr/bin/clang-tidy-18 \
                -DCMAKE_CXX_CLANG_TIDY=/usr/bin/clang-tidy-18 \
                -DBUILD_SHARED_LIBS="$shared" \
                -DPRISM_BUILD_WINELIBS=ON \
                -DPRISM_ENABLE_GDEXTENSION=OFF
              cmake --build "build-${linkage}-${config}" --target prism
            done
          done
