# SPDX-License-Identifier: MPL-2.0
name: Lint Emscripten
on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          diagnostic-endpoint: ""
          extra-conf: |
            substituters = https://cache.nixos.org
            experimental-features = nix-command flakes
      - name: Configure script permissions
        run: |
          chmod -c -R +x tools
      - name: Lint all configurations
        run: |
          nix develop --ignore-environment --keep HOME ".#devShells.x86_64-linux.emscripten-lint" -c ./tools/lint-emscripten.sh
